'use client';
import { useEffect, useRef, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link'; import axios from 'axios';
import { InputText } from 'primereact/inputtext'; import { Calendar } from 'primereact/calendar'; import { Button } from 'primereact/button'; import { Toast } from 'primereact/toast';
import TextEditor from '@/app/components/common/editor';

export default function AnnouncementForm() {
  const { register, handleSubmit, reset, setValue, formState: { errors } } = useForm(); const [description, setDescription] = useState(''); const [fromDate, setFromDate] = useState(null); const [toDate, setToDate] = useState(null); const [loading, setLoading] = useState(false); const toast = useRef(null); const router = useRouter(); const id = useSearchParams().get('id');
  useEffect(() => { if (!id) return; (async () => { try { const res = await axios.get(`/api/announcements/${id}`); const item = res.data.data; reset({ sortNo: item.sortNo, title: item.title, description: item.description }); setDescription(item.description); setFromDate(new Date(item.fromDate)); setToDate(new Date(item.toDate)); } catch { toast.current.show({ severity: 'error', summary: 'Error', detail: 'Could not load announcement' }); } })(); }, [id, reset]);
  const submit = async (data) => { if (!fromDate || !toDate) return toast.current.show({ severity: 'warn', summary: 'Dates required', detail: 'Select both dates' }); if (toDate < fromDate) return toast.current.show({ severity: 'warn', summary: 'Invalid dates', detail: 'To date must be after from date' }); setLoading(true); try { await axios[id ? 'put' : 'post'](id ? `/api/announcements/${id}` : '/api/announcements', { sortNo: Number(data.sortNo), title: data.title, description, fromDate, toDate }); router.push('/admin/announcements'); } catch { toast.current.show({ severity: 'error', summary: 'Error', detail: 'Could not save announcement' }); } finally { setLoading(false); } };
  return <div className="p-[20px] xl:p-[25px] w-full"><Toast ref={toast} /><h2 className="text-[22px] font-[700] mb-3">{id ? 'Update' : 'Add'} Announcement</h2><form onSubmit={handleSubmit(submit)} className="bg-white card-shadow p-[25px]"><div className="max-w-3xl mx-auto space-y-4"><div className="flex flex-col gap-1"><label>Sort Number</label><InputText type="number" min="0" {...register('sortNo', { required: 'Sort number is required', min: { value: 0, message: 'Sort number cannot be negative' } })} /><span className="text-red-500 text-sm">{errors.sortNo?.message}</span></div><div className="flex flex-col gap-1"><label>Title</label><InputText {...register('title', { required: 'Title is required' })} /><span className="text-red-500 text-sm">{errors.title?.message}</span></div><div className="flex flex-col gap-1"><label>Description</label><TextEditor value={description} setEditorContent={setDescription} onChange={(value) => { setDescription(value); setValue('description', value); }} /><input type="hidden" {...register('description', { required: 'Description is required' })} /><span className="text-red-500 text-sm">{errors.description?.message}</span></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-5"><div className="flex flex-col gap-1"><label>From date</label><Calendar value={fromDate} onChange={(e) => setFromDate(e.value)} showIcon /></div><div className="flex flex-col gap-1"><label>To date</label><Calendar value={toDate} onChange={(e) => setToDate(e.value)} minDate={fromDate} showIcon /></div></div><div className="flex justify-center gap-6"><Link href="/admin/announcements" className="cancelbtn px-4 py-2">Cancel</Link><Button type="submit" loading={loading} className="text-white bg-primarycolor px-4 py-2">{id ? 'Update' : 'Save'}</Button></div></div></form></div>;
}
